version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: greenplanep2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql123456
      MYSQL_DATABASE: greenplanep2
      TZ: UTC
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - greenplanep2_mysql_data:/var/lib/mysql

volumes:
  greenplanep2_mysql_data:
